networks:
  rabbitmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.41.0.0/16

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5673:5672"     # Porta AMQP alterada
      - "15673:15672"   # Porta do painel de gerenciamento alterada
    environment:
      - RABBITMQ_DEFAULT_USER=rodrigo
      - RABBITMQ_DEFAULT_PASS=123456
      - TZ=America/Sao_Paulo
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      rabbitmq_net:
        ipv4_address: 172.41.0.10
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning", "--dir", "/data" ]
    volumes:
      - ./redis_data:/data
    environment:
      - TZ=America/Sao_Paulo
    networks:
      rabbitmq_net:
        ipv4_address: 172.41.0.11
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=America/Sao_Paulo
    volumes:
      - ./redisinsight_data:/data
    user: "0:0"
    networks:
      rabbitmq_net:
        ipv4_address: 172.41.0.12
    restart: unless-stopped
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - TZ=America/Sao_Paulo
    ports:
      - "8081:8081"
    depends_on:
      - redis
    volumes:
      - ./redis_commander_data:/home/app/.redis-commander
    networks:
      rabbitmq_net:
        ipv4_address: 172.41.0.13
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - TZ=America/Sao_Paulo
    volumes:
      - ./mongo-data:/data/db
    networks:
      rabbitmq_net:
        ipv4_address: 172.41.0.14

volumes:
  rabbitmq_data:
  redis_data:
  redisinsight_data:
  redis_commander_data:
  mongo-data:
